/*
 * 
 * 
 * 
 */

package frontend_view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mohammadal-ahdal
 */
public class DebugWindow extends javax.swing.JFrame {

    /**
     * Creates new form DebugWindow
     */
    public DebugWindow() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        System.setProperty("com.apple.mrj.application.apple.menu.about.name", "WikiTeX");
        System.setProperty("apple.laf.useScreenMenuBar", "true");
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        initComponents();
    }
    
    public void reInit(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DebugWindow().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cameraProfileAndFramingTabbedPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        com.github.sarxos.webcam.Webcam wc = com.github.sarxos.webcam.Webcam.getDefault();
        wc.open();
        jPanel2 = new com.github.sarxos.webcam.WebcamPanel(wc);
        jPanel2.setFPSDisplayed(true);
        jPanel2.setDisplayDebugInfo(true);
        jPanel2.setImageSizeDisplayed(true);
        jPanel2.setMirrored(true);
        jPanel2.setSize(1920, 1080);
        lolol = new javax.swing.JPanel();
        skeletalRecognitionTabbedPanel = new javax.swing.JPanel();
        skeletalViewPanel = new javax.swing.JPanel();
        profileConfigurationLabel = new javax.swing.JLabel();
        profileConfigurationData = new javax.swing.JLabel();
        skeletalInfoScrollPane = new javax.swing.JScrollPane();
        skeletalInfoContainer = new javax.swing.JPanel();
        palmLabel = new javax.swing.JLabel();
        palmCenterPointLabel = new javax.swing.JLabel();
        palmCenterPointData = new javax.swing.JLabel();
        fingerInfoContainer = new javax.swing.JPanel();
        thumbContainer = new javax.swing.JPanel();
        thumbTitleLabel = new javax.swing.JLabel();
        thumbSaddlePointLabel = new javax.swing.JLabel();
        thumbHingePointLabel = new javax.swing.JLabel();
        thumbSaddlePointData = new javax.swing.JLabel();
        thumbHingePointData = new javax.swing.JLabel();
        thumbSaddleBendAngleLabel = new javax.swing.JLabel();
        thumbHingeBendAngleLabel = new javax.swing.JLabel();
        thumbSaddleBendAngleData = new javax.swing.JLabel();
        thumbHingeBendAngleData = new javax.swing.JLabel();
        thumbTipPointLabel = new javax.swing.JLabel();
        thumbTipPointData = new javax.swing.JLabel();
        indexFingerContainer = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        middleFingerContainer = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        ringFingerContainer = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        pinkyFingerContainer = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Overview", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setSize(new java.awt.Dimension(729, 462));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 375, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Camera Hue", jPanel4);

        javax.swing.GroupLayout lololLayout = new javax.swing.GroupLayout(lolol);
        lolol.setLayout(lololLayout);
        lololLayout.setHorizontalGroup(
            lololLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1139, Short.MAX_VALUE)
        );
        lololLayout.setVerticalGroup(
            lololLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Camera Tint (B/W)", lolol);

        javax.swing.GroupLayout cameraProfileAndFramingTabbedPanelLayout = new javax.swing.GroupLayout(cameraProfileAndFramingTabbedPanel);
        cameraProfileAndFramingTabbedPanel.setLayout(cameraProfileAndFramingTabbedPanelLayout);
        cameraProfileAndFramingTabbedPanelLayout.setHorizontalGroup(
            cameraProfileAndFramingTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        cameraProfileAndFramingTabbedPanelLayout.setVerticalGroup(
            cameraProfileAndFramingTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Camera Profile and Framing", cameraProfileAndFramingTabbedPanel);

        skeletalViewPanel.setBackground(new java.awt.Color(0, 0, 0));
        skeletalViewPanel.setToolTipText("");

        javax.swing.GroupLayout skeletalViewPanelLayout = new javax.swing.GroupLayout(skeletalViewPanel);
        skeletalViewPanel.setLayout(skeletalViewPanelLayout);
        skeletalViewPanelLayout.setHorizontalGroup(
            skeletalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        skeletalViewPanelLayout.setVerticalGroup(
            skeletalViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        profileConfigurationLabel.setText("Configuarion:");

        profileConfigurationData.setText("!NULL");

        skeletalInfoScrollPane.setBorder(null);

        skeletalInfoContainer.setBackground(new java.awt.Color(238, 211, 180));

        palmLabel.setText("Palm");

        palmCenterPointLabel.setText("Center Point:");

        palmCenterPointData.setText("!NULL");

        thumbContainer.setBackground(new java.awt.Color(102, 204, 255));

        thumbTitleLabel.setText("Thumb:");

        thumbSaddlePointLabel.setText("Saddle Point:");

        thumbHingePointLabel.setText("Hinge Point:");

        thumbSaddlePointData.setText("!NULL");

        thumbHingePointData.setText("!NULL");

        thumbSaddleBendAngleLabel.setText("Saddle Bend Angle:");

        thumbHingeBendAngleLabel.setText("Hinge Bend Angle:");

        thumbSaddleBendAngleData.setText("!NULL");

        thumbHingeBendAngleData.setText("!NULL");

        thumbTipPointLabel.setText("Tip Point:");

        thumbTipPointData.setText("!NULL");

        javax.swing.GroupLayout thumbContainerLayout = new javax.swing.GroupLayout(thumbContainer);
        thumbContainer.setLayout(thumbContainerLayout);
        thumbContainerLayout.setHorizontalGroup(
            thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thumbContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thumbTitleLabel)
                    .addGroup(thumbContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(thumbContainerLayout.createSequentialGroup()
                                .addComponent(thumbHingePointLabel)
                                .addGap(18, 18, 18)
                                .addComponent(thumbHingePointData))
                            .addGroup(thumbContainerLayout.createSequentialGroup()
                                .addComponent(thumbSaddlePointLabel)
                                .addGap(18, 18, 18)
                                .addComponent(thumbSaddlePointData))
                            .addGroup(thumbContainerLayout.createSequentialGroup()
                                .addComponent(thumbTipPointLabel)
                                .addGap(18, 18, 18)
                                .addComponent(thumbTipPointData))
                            .addGroup(thumbContainerLayout.createSequentialGroup()
                                .addComponent(thumbSaddleBendAngleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(thumbSaddleBendAngleData))
                            .addGroup(thumbContainerLayout.createSequentialGroup()
                                .addComponent(thumbHingeBendAngleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(thumbHingeBendAngleData)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thumbContainerLayout.setVerticalGroup(
            thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thumbContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thumbTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thumbSaddlePointLabel)
                    .addComponent(thumbSaddlePointData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thumbHingePointLabel)
                    .addComponent(thumbHingePointData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thumbTipPointLabel)
                    .addComponent(thumbTipPointData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thumbSaddleBendAngleLabel)
                    .addComponent(thumbSaddleBendAngleData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thumbContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thumbHingeBendAngleLabel)
                    .addComponent(thumbHingeBendAngleData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        indexFingerContainer.setBackground(new java.awt.Color(255, 51, 255));

        jLabel15.setText("Index Finger:");

        jLabel16.setText("Base Point:");

        jLabel17.setText("Knuckle Point:");

        jLabel18.setText("Distal Phalange Point:");

        jLabel19.setText("Tip Point:");

        jLabel21.setText("!NULL");

        jLabel22.setText("!NULL");

        jLabel23.setText("!NULL");

        jLabel24.setText("!NULL");

        jLabel27.setText("Base Bend Angle:");

        jLabel28.setText("!NULL");

        jLabel29.setText("Knuckle Bend Angle:");

        jLabel30.setText("!NULL");

        jLabel31.setText("Distal PhalangeBend Angle:");

        jLabel32.setText("!NULL");

        javax.swing.GroupLayout indexFingerContainerLayout = new javax.swing.GroupLayout(indexFingerContainer);
        indexFingerContainer.setLayout(indexFingerContainerLayout);
        indexFingerContainerLayout.setHorizontalGroup(
            indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(indexFingerContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24))
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28))
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel32))
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30))
                            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indexFingerContainerLayout.setVerticalGroup(
            indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indexFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        middleFingerContainer.setBackground(new java.awt.Color(255, 51, 51));

        jLabel48.setText("Ring Finger:");

        jLabel49.setText("Base Point:");

        jLabel50.setText("!NULL");

        jLabel51.setText("Knuckle Point:");

        jLabel52.setText("!NULL");

        jLabel53.setText("Distal Phalange Point:");

        jLabel54.setText("!NULL");

        jLabel55.setText("Tip Point:");

        jLabel56.setText("!NULL");

        jLabel57.setText("Base Bend Angle:");

        jLabel58.setText("!NULL");

        jLabel59.setText("Knuckle Bend Angle:");

        jLabel60.setText("!NULL");

        jLabel61.setText("Distal PhalangeBend Angle:");

        jLabel62.setText("!NULL");

        javax.swing.GroupLayout middleFingerContainerLayout = new javax.swing.GroupLayout(middleFingerContainer);
        middleFingerContainer.setLayout(middleFingerContainerLayout);
        middleFingerContainerLayout.setHorizontalGroup(
            middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addGroup(middleFingerContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel52))
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel50))
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel54))
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel56))
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel60))
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel58))
                            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel62)))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        middleFingerContainerLayout.setVerticalGroup(
            middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middleFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middleFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel62))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ringFingerContainer.setBackground(new java.awt.Color(0, 153, 153));

        jLabel33.setText("Middle Finger:");

        jLabel34.setText("Base Point:");

        jLabel35.setText("!NULL");

        jLabel36.setText("Knuckle Point:");

        jLabel37.setText("!NULL");

        jLabel38.setText("Distal Phalange Point:");

        jLabel39.setText("!NULL");

        jLabel40.setText("Tip Point:");

        jLabel41.setText("!NULL");

        jLabel42.setText("Base Bend Angle:");

        jLabel43.setText("!NULL");

        jLabel44.setText("Knuckle Bend Angle:");

        jLabel45.setText("!NULL");

        jLabel46.setText("Distal PhalangeBend Angle:");

        jLabel47.setText("!NULL");

        javax.swing.GroupLayout ringFingerContainerLayout = new javax.swing.GroupLayout(ringFingerContainer);
        ringFingerContainer.setLayout(ringFingerContainerLayout);
        ringFingerContainerLayout.setHorizontalGroup(
            ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(ringFingerContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel37))
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35))
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel39))
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41))
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel45))
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel43))
                            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel47)))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        ringFingerContainerLayout.setVerticalGroup(
            ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ringFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ringFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pinkyFingerContainer.setBackground(new java.awt.Color(51, 204, 0));

        jLabel63.setText("Pinky Finger:");

        jLabel64.setText("Base Point:");

        jLabel65.setText("!NULL");

        jLabel66.setText("Knuckle Point:");

        jLabel67.setText("!NULL");

        jLabel68.setText("Distal Phalange Point:");

        jLabel69.setText("!NULL");

        jLabel70.setText("Tip Point:");

        jLabel71.setText("!NULL");

        jLabel72.setText("Base Bend Angle:");

        jLabel73.setText("!NULL");

        jLabel74.setText("Knuckle Bend Angle:");

        jLabel75.setText("!NULL");

        jLabel76.setText("Distal PhalangeBend Angle:");

        jLabel77.setText("!NULL");

        javax.swing.GroupLayout pinkyFingerContainerLayout = new javax.swing.GroupLayout(pinkyFingerContainer);
        pinkyFingerContainer.setLayout(pinkyFingerContainerLayout);
        pinkyFingerContainerLayout.setHorizontalGroup(
            pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel66)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel67))
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel64)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel65))
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel69))
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel71))
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel74)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel75))
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel73))
                            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel76)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel77)))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        pinkyFingerContainerLayout.setVerticalGroup(
            pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinkyFingerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jLabel65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(jLabel69))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(jLabel71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinkyFingerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(jLabel77))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fingerInfoContainerLayout = new javax.swing.GroupLayout(fingerInfoContainer);
        fingerInfoContainer.setLayout(fingerInfoContainerLayout);
        fingerInfoContainerLayout.setHorizontalGroup(
            fingerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerInfoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fingerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thumbContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indexFingerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ringFingerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(middleFingerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinkyFingerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fingerInfoContainerLayout.setVerticalGroup(
            fingerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerInfoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thumbContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexFingerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ringFingerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(middleFingerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinkyFingerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout skeletalInfoContainerLayout = new javax.swing.GroupLayout(skeletalInfoContainer);
        skeletalInfoContainer.setLayout(skeletalInfoContainerLayout);
        skeletalInfoContainerLayout.setHorizontalGroup(
            skeletalInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skeletalInfoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skeletalInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fingerInfoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(skeletalInfoContainerLayout.createSequentialGroup()
                        .addGroup(skeletalInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palmLabel)
                            .addGroup(skeletalInfoContainerLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(palmCenterPointLabel)
                                .addGap(18, 18, 18)
                                .addComponent(palmCenterPointData)))
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
        skeletalInfoContainerLayout.setVerticalGroup(
            skeletalInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skeletalInfoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(palmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skeletalInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palmCenterPointLabel)
                    .addComponent(palmCenterPointData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fingerInfoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        skeletalInfoScrollPane.setViewportView(skeletalInfoContainer);

        javax.swing.GroupLayout skeletalRecognitionTabbedPanelLayout = new javax.swing.GroupLayout(skeletalRecognitionTabbedPanel);
        skeletalRecognitionTabbedPanel.setLayout(skeletalRecognitionTabbedPanelLayout);
        skeletalRecognitionTabbedPanelLayout.setHorizontalGroup(
            skeletalRecognitionTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skeletalRecognitionTabbedPanelLayout.createSequentialGroup()
                .addComponent(skeletalViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(skeletalRecognitionTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(skeletalRecognitionTabbedPanelLayout.createSequentialGroup()
                        .addComponent(profileConfigurationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(profileConfigurationData)
                        .addGap(0, 306, Short.MAX_VALUE))
                    .addGroup(skeletalRecognitionTabbedPanelLayout.createSequentialGroup()
                        .addComponent(skeletalInfoScrollPane)
                        .addContainerGap())))
        );
        skeletalRecognitionTabbedPanelLayout.setVerticalGroup(
            skeletalRecognitionTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skeletalRecognitionTabbedPanelLayout.createSequentialGroup()
                .addGroup(skeletalRecognitionTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skeletalViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(skeletalRecognitionTabbedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(skeletalRecognitionTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profileConfigurationLabel)
                            .addComponent(profileConfigurationData))
                        .addGap(18, 18, 18)
                        .addComponent(skeletalInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Skeletal Recognition", skeletalRecognitionTabbedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebugWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DebugWindow().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(DebugWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cameraProfileAndFramingTabbedPanel;
    private javax.swing.JPanel fingerInfoContainer;
    private javax.swing.JPanel indexFingerContainer;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel1;
    /*
    private javax.swing.JPanel jPanel2;
    */ private com.github.sarxos.webcam.WebcamPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel lolol;
    private javax.swing.JPanel middleFingerContainer;
    private javax.swing.JLabel palmCenterPointData;
    private javax.swing.JLabel palmCenterPointLabel;
    private javax.swing.JLabel palmLabel;
    private javax.swing.JPanel pinkyFingerContainer;
    private javax.swing.JLabel profileConfigurationData;
    private javax.swing.JLabel profileConfigurationLabel;
    private javax.swing.JPanel ringFingerContainer;
    private javax.swing.JPanel skeletalInfoContainer;
    private javax.swing.JScrollPane skeletalInfoScrollPane;
    private javax.swing.JPanel skeletalRecognitionTabbedPanel;
    private javax.swing.JPanel skeletalViewPanel;
    private javax.swing.JPanel thumbContainer;
    private javax.swing.JLabel thumbHingeBendAngleData;
    private javax.swing.JLabel thumbHingeBendAngleLabel;
    private javax.swing.JLabel thumbHingePointData;
    private javax.swing.JLabel thumbHingePointLabel;
    private javax.swing.JLabel thumbSaddleBendAngleData;
    private javax.swing.JLabel thumbSaddleBendAngleLabel;
    private javax.swing.JLabel thumbSaddlePointData;
    private javax.swing.JLabel thumbSaddlePointLabel;
    private javax.swing.JLabel thumbTipPointData;
    private javax.swing.JLabel thumbTipPointLabel;
    private javax.swing.JLabel thumbTitleLabel;
    // End of variables declaration//GEN-END:variables
}